unlink("~/gz/account_dim",recursive = TRUE)
unlink("~/gz/assignment_dim",recursive = TRUE)
unlink("~/gz/course_dim",recursive = TRUE)
unlink("~/gz/course_section_dim",recursive = TRUE)
unlink("~/gz/enrollment_dim",recursive = TRUE)
unlink("~/gz/module_dim",recursive = TRUE)
unlink("~/gz/module_item_dim",recursive = TRUE)
unlink("~/gz/quiz_dim",recursive = TRUE)
unlink("~/gz/quiz_submission_fact",recursive = TRUE)
unlink("~/gz/user_dim",recursive = TRUE)
unlink("~/datos",recursive = TRUE)
shell('canvasDataCli fetch -c config.js -t user_dim') 
shell('canvasDataCli fetch -c config.js -t enrollment_dim')
shell('canvasDataCli fetch -c config.js -t quiz_dim')
shell('canvasDataCli fetch -c config.js -t quiz_submission_fact')
shell('canvasDataCli fetch -c config.js -t module_dim')
shell('canvasDataCli fetch -c config.js -t module_item_dim')
shell('canvasDataCli fetch -c config.js -t assignment_dim')
shell('canvasDataCli unpack -c config.js -f user_dim quiz_dim enrollment_dim quiz_submission_fact')
shell('canvasDataCli unpack -c config.js -f module_dim')
shell('canvasDataCli unpack -c config.js -f module_item_dim')
shell('canvasDataCli unpack -c config.js -f assignment_dim')
shell('canvasDataCli fetch -c config.js -t account_dim')
shell('canvasDataCli unpack -c config.js -f account_dim')
shell('canvasDataCli fetch -c config.js -t course_dim')
shell('canvasDataCli unpack -c config.js -f course_dim')
shell('canvasDataCli fetch -c config.js -t course_section_dim')
shell('canvasDataCli unpack -c config.js -f course_section_dim')
